# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f41007020f2318a0355e64f04de808beca810df06dba5815a11a166f10c5285a22fcfdfc516c11a4f34b9fbb925b595ca75efd8d486df7e14658e877966ad639

test:
  secret_key_base: 8add1f6f632a9e3e76d42b1f53dc43f4aaf413f593f8bd7a3994bcec9d7609ef89ba04c84355f47435f5cebf9df93a5083458cfc8c92f7cd796741d035ed4433

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
